### ISSUE TITLE
MOD_ID_LIST problem

### ISSUE THREAD

**Issue by bot223** [KagurazakaNyaa/soulmask-docker#3]
There seems to be a character limit, exceeding 13 IDs is abnormal

**Comment by KagurazakaNyaa** [comment]
Please provide an example of a problematic `docker-compose.yml` or a `docker run` command so I can help you troubleshoot the issue.

**Comment by bot223** [comment]
added this parameter：MOD_ID_LIST=3328322545,3337611408,3325629900,3325143163,3325034091,3324992590,3325589784,3325560553,3325592770,3331511657,3327030980,3326990719,3326941063,3324469527
Entering the server prompts missing module: 332446

![17274347468815](https://github.com/user-attachments/assets/7f3d66fc-daf1-4934-af62-33b96d683a26)
Modify to:
MOD_ID_LIST=3328322545,3337611408,3325629900,3325143163,3325034091,3324992590,3325589784,3325560553,3325592770,3331511657,3327030980,3326990719,
This is normal

**Comment by KagurazakaNyaa** [comment]
Please run `ps -ef | grep soulmask` on the host machine and confirm that the output is similar to the following example:
```
$ ps -ef | grep soulmask
1000      430725  430718  1 19:34 ?        00:00:09 /opt/soulmask/WS/Binaries/Linux/WSServer-Linux-Shipping WS Level01_Main -server -SLIENT -log -UTF8Output -SteamServerName="Test" -MaxPlayers=20 -backup=600 -saving=300 -MULTIHOME=0.0.0.0 -Port=7777 -QueryPort=28015 -EchoPort=18888 -online=Steam -forcepassthrough -initbackup -backupinterval=60 -pve -mod="3328322545,3337611408,3325629900,3325143163,3325034091,3324992590,3325589784,3325560553,3325592770,3331511657,3327030980,3326990719,3326941063,3324469527"
```

**Comment by KagurazakaNyaa** [comment]
If you are running with `docker run ...`, try deploying with `docker-compose.yml`.

**Comment by bot223** [comment]
ps -ef | grep soulmask 显示的参数正常，docker run、docker-compose.yml都这样，看了一圈，没有一个服的MOD数量超过12的，应该是服务器本身的问题

**Comment by KagurazakaNyaa** [comment]
那只能等官方开发人员修复了,也许可以在群里催一催,steam页面上的那几个群里都有官方的人在

**Comment by KagurazakaNyaa** [comment]
我重新尝试了一下使用14个mod的情况，现在似乎可以正常使用了，也许需要进一步测试
在日志中可以注意到
```
LogInit: Command Line:  Level01_Main -server -SLIENT -log -UTF8Output -SteamServerName="Test" -MaxPlayers=20 -backup=600 -saving=300 -MULTIHOME=0.0.0.0 -Port=7777 -QueryPort=28015 -EchoPort=18888 -online=Steam -forcepassthrough -initbackup -backupinterval=60 -adminpsw="testtest" -PSW="test" -pve -mod="3328322545,3337611408,3325629900,3325143163,3325034091,3324992590,3325589784,3325560553,3325592770,3331511657,3327030980,3326990719,3326941063,3324469527"

......

[2024.12.04-06.01.41:767][ 51]logHGameInstance: Display: [MOD]begin download 3328322545, (1 of 14)
```
游戏应当已经可以识别到正确数量的modid
